config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#show', via: :get
  resource :dashboard, only: [:show]
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show] do
    post 'follow' => 'following_relationships#create'
  end
  resources :text_shouts, only: [:create]
  resources :photo_shouts, only: [:create]
  resources :shouts, only: [:show]
end

app/models/following_relationship.rb
class FollowingRelationship < ActiveRecord::Base
  belongs_to :follower, class_name: 'User'
  belongs_to :followed_user, class_name: 'User'
end

app/models/photo_shout.rb
class PhotoShout < ActiveRecord::Base
  has_attached_file :image, styles: {
    shout: "200x200>"
  }
  validates_attachment_content_type :image, content_type: %w(image/jpeg image/jpg image/png)
end

app/models/shout.rb
class Shout < ActiveRecord::Base
  belongs_to :user
  default_scope { order("created_at DESC") }
  belongs_to :content, polymorphic: true
end

app/models/text_shout.rb
class TextShout < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
  has_many :shouts

  has_many :followed_user_relationships,
    foreign_key: :follower_id,
    class_name: 'FollowingRelationship'
  has_many :followed_users, through: :following_relationships

  has_many :follower_relationships,
    foreign_key: :followed_user_id,
    class_name: 'FollowingRelationship'
  has_many :followed_users, through: :follower_relationships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @text_shout = TextShout.new
    @photo_shout = PhotoShout.new
    @shouts = current_user.shouts
  end
end

app/controllers/following_relationships_controller.rb
class FollowingRelationshipsController < ApplicationController
  def create
    user = User.find(params[:user_id])
    current_user.followed_users << user
    redirect_to user
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_filter :check_logged_in_user
  def show
  end

  private

  def check_logged_in_user
    if signed_in?
      redirect_to dashboard_path
    end
  end
end

app/controllers/photo_shouts_controller.rb
class PhotoShoutsController < ApplicationController
  def create
    content = build_content
    shout = current_user.shouts.build(content: content)
    if shout.save
      redirect_to dashboard_path
    else
      flash.alert = 'couldnt shout'
      redirect_to dashboard_path
    end
  end

  private

  def build_content
    PhotoShout.new(photo_shout_parameters)
  end

  def photo_shout_parameters
    params.require(:photo_shout).permit(:image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  def show
    @shout = Shout.find(params[:id])
  end
end

app/controllers/text_shouts_controller.rb
class TextShoutsController < ApplicationController
  def create
    content = build_content
    shout = current_user.shouts.build(content: content)
    if shout.save
      redirect_to dashboard_path
    else
      flash.alert = 'couldnt shout'
      redirect_to dashboard_path
    end
  end

  private

  def build_content
    TextShout.new(text_shout_parameters)
  end

  def text_shout_parameters
    params.require(:text_shout).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @shouts = @user.shouts
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shouts_helper.rb
require 'digest/md5'

module ShoutsHelper
  def gravatar user, size = 48
    digest = Digest::MD5.hexdigest(user.email)
    image_tag("http://gravatar.com/avatar/#{digest}?s=#{size}")
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def follow_button user
    button_to 'Follow', user_follow_path(user)
  end
end

app/views/dashboards/show.html.erb
<%= form_for @text_shout do |form| %>
  <%= form.text_field :body, placeholder: 'Should content here' %>
  <%= form.submit 'Shout!' %>
<% end %>

<%= form_for @photo_shout do |form| %>
  <%= form.file_field :image %>
  <%= form.submit 'Shout!' %>
<% end %>

<%= render @shouts %>

app/views/homes/show.html.erb
Welcome to Shouter

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Shouter</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>
<body>
  <div>
    <% if signed_in? %>
      <%= link_to current_user.username, dashboard_path %>
      <%= link_to 'Sign out', session_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign in', new_session_path %>
      <%= link_to 'Sign up', new_user_path %>
    <% end %>
  </div>
  <% if alert %>
    <p><%= alert %></p>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/photo_shouts/_photo_shout.html.erb
<%= link_to image_tag(photo_shout.image.url(:shout)), photo_shout.image.url %>

app/views/shouts/_shout.html.erb
<%= div_for shout do %>
  <%= gravatar shout.user %>
  <%= link_to shout.user.username, shout.user %>
  shouted
  <div>
    <%= render shout.content %>
  </div>
  <%= link_to time_ago_in_words(shout.created_at), shout %>
<% end %>

app/views/shouts/show.html.erb
<%= render @shout %>

app/views/text_shouts/_text_shout.html.erb
<%= text_shout.body %>

app/views/users/new.html.erb
<%= form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>
  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<%= follow_button @user %>
<%= render @shouts %>